# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{parsley-ruby}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kyle Maxwell"]
  s.date = %q{2009-12-28}
  s.description = %q{XML/HTML Parser}
  s.email = %q{kyle@kylemaxwell.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "README",
     "Rakefile",
     "VERSION",
     "ext/cparsley.c",
     "ext/extconf.rb",
     "lib/parsley.rb",
     "parsley-ruby.gemspec",
     "test/test_parsley.rb",
     "test/yelp-benchmark.rb",
     "test/yelp-home.html",
     "test/yelp-home.let",
     "test/yelp.html"
  ]
  s.homepage = %q{http://github.com/fizx/parsley-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib", "ext"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby binding for parsley}
  s.test_files = [
    "test/test_parsley.rb",
     "test/yelp-benchmark.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["> 0.0.0"])
    else
      s.add_dependency(%q<json>, ["> 0.0.0"])
    end
  else
    s.add_dependency(%q<json>, ["> 0.0.0"])
  end
end

